name: arcpy_parquet

channels:
  - esri
  - conda-forge

dependencies:
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - nodejs
  - pip
  - pip:
    - build
    - bump2version
    - zensical
    - mkdocstrings-python
    - twine
